env:
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
  linebreak-style: 0
  quotes:
    - error
    - single
  semi:
    - error
    - never
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/no-non-null-assertion': 0
